name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: 1.12.3
          args: release --rm-dist
        env:
          LDFLAGS: "-s -v"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
